global:
  sysdig:
     accessKeySecret: sysdig-agent # Access Key Secret - from <sysdig URL>/secure/#/settings/agentInstallation
     region: au1
     tags:
       environment: CHANGE_ME
  clusterConfig:
     name: CHANGE_ME # Name of your cluster so Sysdig can identify it
  kspm:
      deploy: true
agent:
  enabled: true # Enables sysdig-agent which does Falco syscall Threat Detection, Activity Audit, Image Profiling, ML, Drift Detection etc...
  sysdig:
    settings:
      app_checks_enabled: false # Disable legacy appchecks for Sysdig Monitor
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi

clusterShield:
  cluster_shield:
    features:
      audit:
        enabled: true
      container_vulnerability_management: 
        enabled: true # Enable Cluster Scanner
      posture:
        enabled: true
      admission_control:
        enabled: true
        dry_run: false # default is true
        container_vulnerability_management: 
          enabled: true  # Enable Vulnerability AC checking
    log_level: info 
  enabled: true
  replicaCount: 1

nodeAnalyzer:
  enabled: true
  nodeAnalyzer:
    benchmarkRunner:
      deploy: false
    runtimeScanner:
      deploy: false
  secure:
    vulnerabilityManagement:
      newEngineOnly: true

admissionController:
  enabled: false

kspmCollector:
  enabled: false
